---
- name: Generate random password for Database
  ansible.builtin.shell: "openssl rand -base64 32 | tr -c 'a-zA-Z0-9' '_'"
  register: db_password
  changed_when: false

- name: Get Current GCP Project ID (if any)
  ansible.builtin.shell: gcloud config get-value project
  register: gcp_project_id
  changed_when: false
  ignore_errors: yes

- name: Get Current Azure Subscription ID (if any)
  ansible.builtin.shell: az account show --query "id" -o tsv
  register: azure_subscription_id
  changed_when: false
  ignore_errors: yes

- name: Display Current GCP Project ID
  debug:
    msg: "Current GCP Project ID is: {{ gcp_project_id.stdout }}"

- name: Debug Azure Subscription ID
  debug:
    msg: "Azure Subscription ID: {{ azure_subscription_id.stdout }}"

- name: Create or update the terraform .tfvars file
  template:
    src: terraform_vars.tfvars.j2
    dest: ../../terraform/ansiblefeeded.tfvars

- name: Display success message
  debug:
    msg: "Terraform tfvars file has been updated successfully."
