#SPDX-License-Identifier: MIT-0
---
# tasks file for ansible/roles/gcp/tasks/terraform_pulzen_mongo_atlas_deploy.yml

- name: Initialize Terraform
  ansible.builtin.shell:
    cmd: terraform init
    chdir: ../../terraform
  register: terraform_init
  changed_when: false

- name: Fail if Terraform initialization failed
  ansible.builtin.fail:
    msg: "Terraform initialization failed."
  when: terraform_init.rc != 0

- name: Apply Terraform configuration
  ansible.builtin.shell:
    cmd: terraform apply -auto-approve -var-file=ansiblefeeded.tfvars
    chdir: ../../terraform
  register: terraform_apply
  changed_when: false

- name: Get Terraform output
  ansible.builtin.shell:
    cmd: terraform output -json
    chdir: ../../terraform
  register: terraform_output
  changed_when: false

- name: Display Terraform output
  debug:
    msg: "{{ terraform_output.stdout }}"
